name: CMake CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++

          - os: ubuntu-latest
            cc: clang
            cxx: clang++

          - os: windows-latest
            cc: cl
            cxx: cl

    steps:
      - uses: actions/checkout@v4

      # Install vcpkg
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11

      # Configure CMake
      - name: Configure CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: >
          cmake
          -B build
          -S .
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      # Build
      - name: Build
        run: cmake --build build --config Release

      # Test (optional)
      - name: Test
        working-directory: build
        run: ctest --output-on-failure --build-config Release
